server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  signerKey: "jO/x0Ap+0yNcRCKWwcq+pcugch7d9vjeAeL/2XP/yB1AzRWJc7r4jsv+edCXjrxb"
